#!/bin/bash

echo "Current time:"
date
echo "instagram_pgh:"
mongo instagram --eval "db.instagram_pgh.count();"
echo "flickr_pgh:"
mongo flickr --eval "db.flickr_pgh.count();"
echo "twitter_pgh:"
mongo tweet --eval "db.tweet_pgh.count();"

echo "twitter_sf:"
mongo tweet --eval "db.tweet_sf.count();"
echo "twitter_ny:"
mongo tweet --eval "db.tweet_ny.count();"
echo "twitter_houston:"
mongo tweet --eval "db.tweet_houston.count();"
echo "twitter_detroit:"
mongo tweet --eval "db.tweet_detroit.count();"
echo "twitter_chicago:"
mongo tweet --eval "db.tweet_chicago.count();"
echo "twitter_seattle:"
mongo tweet --eval "db.tweet_seattle.count();"
echo "twitter_cleveland:"
mongo tweet --eval "db.tweet_cleveland.count();"
echo "twitter_miami:"
mongo tweet --eval "db.tweet_miami.count();"
echo "twitter_london:"
mongo tweet --eval "db.tweet_london.count();"
